name: System testing

on:
  pull_request:
    branches:
      - master

jobs:
  run_system_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run the test suite
        run: ./docker/rpms/build-and-install-rpms.sh --with-system-tests rl8 docker/rpms/Rocky_Linux_8/Rocky_Linux_8.dockerfile
